#!/bin/bash

# Build script for Arduino projects.
# Copyright (C) 2018 Mithat Konar (https://mithatkonar.com)
# License: LGPL v3

# ---------------------
# --- Configuration ---
# ---------------------
CONF_FILE=arduino.conf

# -----------
# --- GO! ---
# -----------
### get parameters
if [[ -f $CONF_FILE ]] ; then
    source arduino.conf
else
    echo "Config file '$CONF_FILE' not found." > /dev/stderr
    exit 2;
fi

action=$1
source_file=$(ls -1 *.ino)

### test parameters
if [[ -z "$ARDUINO_PATH" ]] ; then
    echo "The ARDUINO_PATH is not specified." > /dev/stderr
    exit 1
fi

if [[ -z "$BUILD_PATH" ]] ; then
    echo "The BUILD_PATH is not specified." > /dev/stderr
    exit 1
fi

if [[ -z "$action" ]] ; then
    echo "No action was specified." > /dev/stderr
    exit 1
fi

if [[ -z "$source_file" ]] ; then
    echo "Source ino file not found." > /dev/stderr
    exit 1
fi

### run with it
arduino_cmd=$ARDUINO_PATH/arduino
output_path=$BUILD_PATH

# construct board options
board_options=$BOARD_PACKAGE:$BOARD_ARCHITECTURE:$BOARD
if [[ x$BOARD_PARAM != x ]] ; then
	board_options=$board_options:$BOARD_PARAM
fi

# parse the action
if [[ "x$action" == "x" ]] ; then
	action=build
fi

case $action in
clean)
    dothis="rm -r $output_path"
    echo "$dothis"
    $dothis
    rv=$?
    ;;
build)
    mkdir -p $output_path
    echo "building ..."
    echo $arduino_cmd --board $board_options --pref build.path=$output_path --verify $source_file
    $arduino_cmd --board $board_options --pref build.path=$output_path --verify $source_file
    rv=$?
    ;;
upload)
    echo "uploading ..."
    $arduino_cmd --board $board_options --pref build.path=$output_path --upload --port $PORT $source_file
    rv=$?
    ;;
monitor)
    echo "Monitoring on $PORT at $SPEED baud..."
    gtkterm -p $PORT -s $SPEED # &
    rv=$?
    ;;
*)
    message="Unknown option"
    rv=1
    ;;
esac

exit $rv
